dile_vt: GM blending
webosbrew/hyperion-webos pull request #21
Opened 2021-12-21 23:19 UTC by Informatic

On K3LP / webOS 3.8 I got these findings:
* GM is not able to go down to 192x108, lowest working resolution here is 240x135.
* Approximate frame processing times starts at around 13ms, but then settles around 9-10ms. This means we can *barely* manage steady 60fps if we count in normal system CPU usage spikes.

This does not implement video/UI layer toggling yet. We likely want to *also* detect if the video is actually on-screen (there was a DILE_VT call for that...) and then drop whole alpha blending step.

Timings breakdown for some sample run:
```
GM_CaptureGraphicScreen: 2507us
ABGRToARGB from GM to malloced memory: 3667us
RGB24ToARGB from VFB to malloeced memory: 2953us
ARGBBlend: 222us
ARGBToRGB24: 136us
Hyperion callback: 890us
```

2021-12-24 00:23 UTC, Informatic commented
4h of testing - dropping down to 30fps here helped with performance significantly, and also probably alleviated some minor stutters/latency spikes I've noticed before. Not sure which part of my setup was the source of that (webOS → ethernet → x86_64 box running hyperion.ng → wifi → esp32 with ws2812) but something worth noting.

2022-01-03 19:47 UTC, Informatic commented
This has been fairly well tested on K3LP and works great. Shall we merge it now?

2022-01-07 17:14 UTC, TBSniller commented
@Informatic: It's not really right, that it is for WebOS 5 TVs. Firstly I had problems getting a capture in which the frames weren't pixel pulb in older versions. Now I can't even run it because of a missing library:
`Failed to load backend library: /media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/libdile_vt_backend.so, error: libgm.so.1: cannot open shared object file: No such file or directory
`
Maybe libgm should also be loaded dynamicly since libdile_vt is working but needs some debugging and fixing on at least my  WebOS 5 TV.

2022-01-07 17:16 UTC, TBSniller requested changes
WebOS 5 support isn't really right.

2022-01-07 17:17 UTC, TBSniller requested changes
Maybe gm can also be loaded dynamically.

2022-01-07 17:25 UTC, Informatic commented
Indeed. We should probably move graphics capture into either modules
loadable by capture backends, or move blending/frame processing out of
capture backends and into the "core" altogether.

On Fri, 7 Jan 2022, 18:18 TBSniller, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Maybe gm can also be loaded dynamically.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/webosbrew/hyperion-webos/pull/21#pullrequestreview-846821043>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIUEXTONKNTSMUVWKVK77DUU4N4VANCNFSM5KRIVQWQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-05 13:20 UTC, tuxuser commented
Superseded by #43

2022-07-05 13:20 UTC, closed without merging