Switching to a native service
webosbrew/hyperion-webos pull request #24
Opened 2021-12-26 22:11 UTC by TBSniller

So I'm ready rewriting hyperion-webos to a native webOS-service. 
It's also possible to run it from command line, logs will be redirected to PmLog.
I don't know why, but we have a huge performance improvement with using libvtcapture and the native service. Maybe it's the same for other backends. 
The UI (PicCap) is also more responsive. 

@Informatic @tuxuser @mariotaku Can some of you please review my changes? Doesn't want to break something.

The CI-Task has to be updated. Want to fix it when https://github.com/webosbrew/tv-native-apis/pull/13 is merged. 

Thanks!

2021-12-26 22:22 UTC, Informatic commented on src/backends/libdile_vt.c
> +    PmLogError(logcontext, "DILECPTSTART", 0, "[DILE_VT] framerate divider: %d\n", output_state.framerate);
Most of these are not errors, more like debug. Not sure if `PmLogError` actually emits messages marked as errors, sorry.

2021-12-26 22:27 UTC, Informatic commented on src/main.c
> +    fullpath[length-14] = '\0';       //Assuming binary is called hyperion-webos = 14 chars | maybe TODO detection
What you are looking for here is likely [`dirname`](https://linux.die.net/man/3/dirname)?

2021-12-27 07:20 UTC, Informatic requested changes
Without any testing yet, in general, looks good enough. Please take a look at some of my nits.

I feel like we could use some linter/autoformatter/analyzer (eg. to detect unsafe calls like strcpy/strcat...) - @mariotaku do you have any experience/opinions on that?

I will wrap up a quick unified logging example today.

I think there should be a way of automatically detecting execution from within ls-hubd (running as a service) - I can look into it today.

Also I remember you mentioning handling `SIGCONT` - can you add that as well?

2021-12-27 07:20 UTC, Informatic commented on src/main.c
> +        if (_address == "")
That check is invalid - it should be something like `if (strcmp(_address, "") == 0)`

2021-12-27 07:20 UTC, Informatic commented on src/main.c
> +            if (_address == "" || _backend == "" || config.fps < 0 || config.fps > 60){
same string compares comment as above

2021-12-27 07:20 UTC, Informatic commented on src/main.c
> +int loadSettings(){
most of our API uses `snake_case` naming, please follow that.

2021-12-27 07:20 UTC, Informatic commented on src/main.c
> +    if(_configpath == ""){
same string compare comment

2021-12-27 07:20 UTC, Informatic commented on src/main.c
> +        strcat(confpath, conffile);
I am not 100% sure, but I feel like we could extract "base path" once, somewhere at the beginning of `main()` (since we use it multiple times), and then use that here via `snprintf`, something like so: `snprintf(confpath, FILENAME_MAX, "%s/%s", base_path, conffile);`

2021-12-27 07:20 UTC, Informatic commented on src/main.c
> +int loadSettings(){
I think it would also make some sense to extract settings handling into a separate code file?

2021-12-27 07:20 UTC, Informatic commented on src/main.c
> +bool start(LSHandle *sh, LSMessage *message, void *data)
I would prepend these with something like `handle_` to make it absolutely clear this is part of luna service handling.

2021-12-27 07:20 UTC, Informatic commented on src/main.c
> +    j_release(&parsed);
I think we may be leaking `jobj` declared above. Also `parsed` is not released in some code paths here as well.

2021-12-27 07:20 UTC, Informatic commented on src/main.c
> +    jobj = jobject_create();
this is leaked

2021-12-27 07:20 UTC, Informatic commented on src/main.c
> +    jobj = jobject_create();
this is leaked

2021-12-27 07:20 UTC, Informatic commented on src/main.c
> +        retstr = jval_to_string(parsed, "stdoutString", "No value!");
~~this string is leaked~~ nevermind, just realized this is the final thing before exit...

2021-12-27 17:45 UTC, TBSniller commented on src/backends/libdile_vt.c
> +    PmLogError(logcontext, "DILECPTSTART", 0, "[DILE_VT] framerate divider: %d\n", output_state.framerate);
No problem, changed some messages. 
Yeah you can set the outputted loglevels using PmLogCtl, this is what then takes effect when receiving the logs.

2021-12-27 17:47 UTC, TBSniller commented on src/main.c
> +    strcat(libpath, library_filename);
I've Googled for it, but everywhere is (also logical) stated, that extending its own LD_PATH var could be a possible security risk.

2021-12-27 17:51 UTC, mariotaku commented
@Informatic For unsafe function calls I just use text search. For binary compatibility we can use https://github.com/webosbrew/native-dev-utils/blob/main/scripts/verify-symbols.sh .

2021-12-27 18:01 UTC, TBSniller commented on src/main.c
> +    fullpath[length-14] = '\0';       //Assuming binary is called hyperion-webos = 14 chars | maybe TODO detection
Yeah - thanks, worked!

2021-12-27 18:04 UTC, TBSniller commented on src/main.c
> +    if(_configpath == ""){
corrected, thx!

2021-12-27 18:04 UTC, TBSniller commented on src/main.c
> +            if (_address == "" || _backend == "" || config.fps < 0 || config.fps > 60){
corrected, thx!

2021-12-27 18:04 UTC, TBSniller commented on src/main.c
> +        if (_address == "")
corrected, thx!

2021-12-27 18:15 UTC, TBSniller commented on src/main.c
> +int loadSettings(){
Never noticed that something like this exists.. :D Changed it, thanks!
I've tried to extract these into another .c file, but failed.. Would need some help, I couldn't figure out how to handle this import stuff..

2021-12-27 18:20 UTC, TBSniller commented on src/main.c
> +bool start(LSHandle *sh, LSMessage *message, void *data)
Corrected, called it method_

2021-12-27 18:22 UTC, TBSniller commented on src/main.c
> +    jobj = jobject_create();
corrected, thx

2021-12-27 18:26 UTC, TBSniller commented on src/main.c
> +    jobj = jobject_create();
corrected, thx!

2021-12-27 18:27 UTC, TBSniller commented on src/main.c
> +    j_release(&parsed);
I think I've found all. There also was a leak fo `tosave` in a if for error handling

2021-12-27 18:57 UTC, TBSniller commented on src/main.c
> +        strcat(confpath, conffile);
corrected it to use it only one time. 
Used strcat, is this ok?

2021-12-27 18:59 UTC, TBSniller commented
@Informatic corrected your inputs. Would you like to check again? 
Thanks!

2021-12-30 20:22 UTC, Informatic commented
A couple of final comments - we can easily check if we are running as a service or not by checking if `LS_SERVICE_NAMES` environment variable exists and is non-empty. We can leave it for later, just as a convenience feature, so that one doesn't need to explicitly add CLI option.
https://github.com/openwebos/luna-service2/blob/0f384298acde1f3a8bcc509401b1fa7a33ca44f7/src/ls-hubd/hub.c#L775-L776

I think we may want to temporarily ship new `elevate-service` binary in `piccap` package for a couple of versions and then run it here, instead of the one that's shipped with homebrew channel:
https://github.com/webosbrew/hyperion-webos/pull/24/files#diff-e0cf5b28d9b6b600f0af2bc78e8fd30ec675fd731a5da86f0c4283ffc0e40176R267

Ability to elevate native services via "official" `elevate-service` script will definitely be useful (and I want to release it soon in a homebrew channel update), but there's not much of a downside to shipping that script together with piccap - and asking people to update homebrew channel app beforehands sounds very error-prone.

2021-12-30 20:32 UTC, Informatic commented
Tested it out, seems to generally work, though fails on any restart - either manual, or via turning the TV off and on - possibly related to `libdile_vt` cleanup handling being broken, will look into that in a minute.

2021-12-30 21:21 UTC, Informatic commented
I've properly renamed `capture_thread` in main to `connection_thread`, and moved over hyperion connection initialization into that function with proper reconnections (with 1s delay inbetween) - we can add reporting of connection status itself, since now service start *will not fail* if hyperion connection fails.

2021-12-31 08:40 UTC, TBSniller commented
Cool very nice! 
Do you then want to create an issue for this CLI env detection, or should I create one? 
There is also a little "bug" in autostart. Haven't exited in the autostart script, that's possibly why dev-mode script is failing and failback mode is activated after second restart. Will fix it.
I'm remembering testing with @snipah to get autostart *fully* working. We had tried to recieve SIGCONT, but weren't able to get it and gave up.

2022-01-01 09:51 UTC, Informatic approved these changes
OK, I think this is ready for merging now.

Logging refactor will be filed in a separate PR.

2022-01-01 21:31 UTC, TBSniller commented
Oh I'm sorry, I thought you can also merge @Informatic

2022-01-01 21:32 UTC, merged

2022-01-01 21:33 UTC, Informatic commented
Yeah, I can, but in most common setups I was participating in, it's the PR submitter that finally merges in the change (if they have commit access) :)

Just a miscommunication.

2022-01-01 22:10 UTC, TBSniller commented
Ahhh I see, I'm sorry, as you know not my daily business - but now I will know it :D