CI: Use buildroot toolchain for building
webosbrew/hyperion-webos pull request #57
Opened 2022-03-13 20:59 UTC by tuxuser

* Use webOS buildroot toolchain: https://github.com/openlgtv/buildroot-nc4/
   - Brings down minimum required glibc to v2.12.2
* For compatibility with glibc 2.12.2: Link `librt` explicitly
* Forward `CMAKE_TOOLCHAIN_FILE` cmake parameter to `libyuv` build

2022-03-18 00:53 UTC, Informatic requested changes

2022-03-18 00:53 UTC, Informatic commented on .github/workflows/build.yml
> +  TOOLCHAIN_URL: https://github.com/openlgtv/buildroot-nc4/releases/latest/download/arm-webos-linux-gnueabi_sdk-buildroot.tar.gz
I'd rather have this pinned to a specific version (and possibly with sha256sum check too)

2022-03-18 00:54 UTC, Informatic commented on libyuv/CMakeLists.txt
>    URL https://chromium.googlesource.com/libyuv/libyuv/+archive/fdc71956bdade0012b0628b5011b567c06c72308.tar.gz
I need to retest this personally, but the last time I tried this CMake was unable to download a dependency over TLS due to missing `https` support in libcurl. I assume this has already been fixed in latest toolchain release.

2022-03-18 01:08 UTC, tuxuser commented on libyuv/CMakeLists.txt
>    URL https://chromium.googlesource.com/libyuv/libyuv/+archive/fdc71956bdade0012b0628b5011b567c06c72308.tar.gz
yeah, no such issue occured when trying with the buildroot toolchain at least.

2022-03-18 01:09 UTC, tuxuser commented on .github/workflows/build.yml
> +  TOOLCHAIN_URL: https://github.com/openlgtv/buildroot-nc4/releases/latest/download/arm-webos-linux-gnueabi_sdk-buildroot.tar.gz
Ok, sounds reasonable, will implement that.

2022-03-18 01:20 UTC, tuxuser commented
* Changed toolchain tarball to versioned URL
* Verify sha256 hash of downloaded tarball

2022-04-23 19:13 UTC, Informatic approved these changes

2022-04-23 22:30 UTC, merged