Add local unix socket support
webosbrew/hyperion-webos pull request #86
Opened 2022-07-20 13:17 UTC by sundermann

Local unix socket support was added in HyperHDR in https://github.com/awawa-dev/HyperHDR/commit/1100093068196a53eff5f856f0eaaf8e43ca229f

Local unix sockets are automatically used when the hostname is set to "/tmp/hyperhdr-domain" which is hardcoded in HyperHDR. On my TV local sockets are around 20-30% faster.

2022-09-25 18:20 UTC, TBSniller commented
Hey there, 

thanks again for contribution!
We have mergend unicapture branch to main. Could you please update your PR to also merge it into main? 

Thanks!

2022-09-27 14:11 UTC, asturel commented on src/settings.c
> +    if ((value = jobject_get(source, j_cstr_to_buffer("unix-socket"))) && jis_boolean(value))
typo? it stored as "unix_socket"

2022-09-27 20:27 UTC, asturel commented on src/service.c
> +        service->settings->address = "127.0.0.1";
this breaks reconnect, once it disconnected it wants to connect to "127.0.0.1" in  '_connect_unix_socket'

2022-09-27 20:49 UTC, sundermann commented on src/settings.c
> +    if ((value = jobject_get(source, j_cstr_to_buffer("unix-socket"))) && jis_boolean(value))
Thanks, I have addressed this

2022-09-27 20:50 UTC, sundermann commented on src/service.c
> +        service->settings->address = "127.0.0.1";
Good catch, I am no longer overwriting the address.

2022-09-28 21:45 UTC, tuxuser requested changes
See comments

2022-09-28 21:45 UTC, tuxuser commented on src/service.c
> +    }
Please move this piece of code / overwrite to main.c, after parse_options was called.

Basically overwriting address in global variable `settings` by doing `settings.address = "127.0.0.1`

2022-09-28 21:45 UTC, tuxuser commented on src/service.c
> +    }
Same comment above

2022-09-28 21:45 UTC, tuxuser commented on src/hyperion_client.c
> -    struct sockaddr_in serv_addr;
Add checking for `/tmp/hyperhdr-domain` here. Iterate over constant array of possible filelocations, in case Hyperion.NG implements local unix socket support too.

If such unix socket handle is found, use it as parameter to `_connect_unix_socket`.

2022-09-28 21:47 UTC, sundermann commented on src/service.c
> +    }
That won't work in case of a reconnect.

2022-09-28 21:49 UTC, tuxuser commented on src/service.c
> +    }
Can you explain in more detail in which case it would break?

2022-09-28 21:51 UTC, sundermann commented on src/hyperion_client.c
> -    struct sockaddr_in serv_addr;
Does this mean we should remove the command line option?

2022-09-28 22:04 UTC, tuxuser commented on src/hyperion_client.c
> -    struct sockaddr_in serv_addr;
No, the cmdline is fine and useful in this case. Just when it knows that a "local unix domain socket" is desired, it should check and use such, if available.

Case 1: No unix domain socket desired
- Supplied IP and Port is used as-is

Case 2: Unix domain socket is desired
- Hardcode ddress to 127.0.0.1 for HTTP RPC JSON communication to the daemon
- Before connecting the socket for flatbuffer data, check if known unix domain sockets exist and use them - otherwise fall back to 127.0.0.1.

2022-09-28 22:07 UTC, sundermann commented on src/service.c
> +    }
`unix_socket` is just a boolean value so where would the unix socket address be stored if it's already overriden just after parsing options. I can only think of making this work by changing `unix_socket` to be a char* containing the socket address.

2022-09-28 22:13 UTC, tuxuser commented on src/service.c
> +    }
Why does the target address/path for the socket need to be stored?

On a later call to `hyperion_client` it will receive the flag unix_socket again and know that it has to do the scanning for path `/tmp/hyperhdr-domain` again - to see if its still available.

The logic stays the same.
The overwrite to address `127.0.0.1` is really just used to enable communication to the JSON RPC, when unix domain socket is used.

2022-09-28 22:14 UTC, sundermann commented on src/hyperion_client.c
> -    struct sockaddr_in serv_addr;
I'm not convinced this is the best option. This tightly couples hyperion-webos to a list of unix sockets which are provided by external software and might change in future. As you pointed out if hyperion.ng were to add a local socket this means that hyperion-webos needs changes as well.

2022-09-28 22:20 UTC, sundermann commented on src/service.c
> +    }
Yes, I misunderstood your idea at first thinking you wanted to compare the hostname against a list of known sockets. However in fact you want to scan if a specific local socket is available. I agree the second idea can work but still I don't like the idea of scanning against a hardcoded list because the socket address could change or hyperion.ng decides to implement local sockets as well.

2022-09-28 22:24 UTC, sundermann commented on src/service.c
> +    }
Another issue is that the -a parameter is still mandatory even though in case of local sockets -a is not mandatory and overwritten making it a bit unintuitive to use.

2022-09-28 22:38 UTC, tuxuser commented on src/service.c
> +    }
agreed, so the flow is:
- Set /tmp/hyperhdr-domain in the IP address field
- Set whatever in port or leave it the default by not providing it

Result: unix domain socket is used for flatbuffers, Tcp socket for json rpc.

Sounds good!

2022-09-28 22:58 UTC, sundermann commented on src/service.c
> +    }
Yes, that is how it is supposed to work.

2022-10-02 21:58 UTC, sundermann commented
Anything missing on this PR?

2022-10-02 22:02 UTC, tuxuser commented
Testing it currently

2022-10-02 22:10 UTC, tuxuser commented
Yup, works fine. Please cleanly rebase against main and correct the linting, then we should be good to go. cheers

2022-10-02 22:32 UTC, TBSniller commented
Thanks!

2022-10-02 22:32 UTC, merged